apiVersion: v1
kind: Service
metadata:
  labels:
    app: Dev
  name: dev-service
  namespace: dev-deployment
spec:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: Dev
  type: NodePort
