apiVersion: v1
kind: Namespace
metadata:
  name: dev-deployment
  labels:
    apps: web-based
  annotations:
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: dev-deployment
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrs-core
  labels:
    app: Dev
  namespace: dev-deployment
  annotations:
    monitoring: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Dev
  template:
    metadata:
      labels:
        app: Dev
    spec:
      containers:
      - image: steju480/qdrscore1.v1:latest
        name: qdrs
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: Dev
  name: dev-service
  namespace: dev-deployment
spec:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: Dev
  type: NodePort
